### ISSUE TITLE
error within vaadin text fields (text input fields vanish on click)

### ISSUE THREAD

**Issue by AstroTorch** [languagetool-org/languagetool#10615]
Hello,

with one of the latest LanguageTool updates, we have errors within vaadin text fields.

You can easily reproduce the error here:

https://vaadin.com/docs/v23/components/text-area
1. Activate LanguageTool
2. Click on one of the text fields and it should vanish, without an option to enter values

With deactivated plugin it works as expected.

Tested with the following browsers:
- Chrome
- Firefox
- Edge
- Brave

**Comment by benocms** [comment]
The problem also exists in Vaadin 24.

**Comment by tiff** [comment]
Thanks, we'll investigate

**Comment by tiff** [comment]
This should be fixed now

**Comment by danielnaber** [comment]
See https://github.com/languagetool-org/languagetool/issues/10806 for a reproducible case that's not fixed yet
