### ISSUE TITLE
Space removal bug with Google Docs

### ISSUE THREAD

**Issue by timtombam104** [languagetool-org/languagetool#11292]
When using the browser plugin with Google Docs and replacing an incorrectly spelled word or adding a comma, the space following the replaced word is also removed. This leads to a chain of errors in the sentence as if you then click the error to add a space then the space following these joined words is also removed.

The issue occurs on both Firefox and Chrome, but did not occur when typing this ticket, so the issue appears to only be with Google Docs.

If needed, I can provide a video or GIF of the error.

**Comment by tiff** [comment]
This has been fixed with version v8.18.11 of our Chrome extension. Firefox will take a little longer until fixed

**Comment by gabinmm** [comment]
Hello, by today, 20/03/2025, this bug still occurs. I have problems on Google Docs, but not in this GitHub or on Canva.
