### ISSUE TITLE
comment in examples again, now that tests are more strict?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2511]
The tests of the correct examples will be made more strict: they didn't work properly in cases with a text in the `<example>...</example>` that's more than one sentence.

**Comment by danielnaber** [comment]
@MikeUnwalla @arysin @MikeUnwalla @marcoagpinto Could you check the examples from [this commit](https://github.com/languagetool-org/languagetool/commit/9a4f1e36c5d9a15056d656ddfe102da7fc84159c) and see whether the commented-out examples can be commented in again, e.g. by adding antipatterns where needed?

**Comment by MikeUnwalla** [comment]
@danielnaber , confirmed. Will do for English.

**Comment by danielnaber** [comment]
> Now, testrules gives a warning if the example contains triggers_error or if it does not:

This should now be fixed. There might be more cases where the checks do not match the real behavior 100%, I'll be working on that later.

**Comment by MikeUnwalla** [comment]
@danielnaber , thanks. testrules works fine with `triggers_error `.

It would be nice to have a way to prevent the FP. (A regexp as an antipattern?)

**Comment by MikeUnwalla** [comment]
> There might be more cases where the checks do not match the real behavior

The testrules/triggers_error problem still occurs with the commented example in THE_LATER_LATTER

**Comment by danielnaber** [comment]
@arysin Could you have a look at line 351 in `PatternRuleTest`(`if (lang.getShortCode().matches("gl|eo|ar|br|ca|zh|uk")) `) and see why the Ukrainian tests fail when "uk" is removed from the regex? This makes the tests even more strict, i.e. there was another case of tests that didn't properly simulate checking the rules as LT usually does.

**Comment by danielnaber** [comment]
@jaumeortola  @sohaibafifi See me comment above to @arysin, the same applies for Arabic and Catalan, could you check it?

**Comment by arysin** [comment]
@danielnaber Yes, same problem: missing PARA_END - I've pushed a fix and removed "uk"

**Comment by danielnaber** [comment]
@MikeUnwalla 

> The testrules/triggers_error problem still occurs with the commented example in THE_LATER_LATTER

That's probably because of the `or`, which doesn't play well together with `triggers_error`. No easy fix in sight, sorry.
