### ISSUE TITLE
Another error, "not a language code known to LanguageTool"

### ISSUE THREAD

**Issue by madmanRB** [languagetool-org/languagetool#3666]
same conditions as last time, new message though and this message is super long, I have a 1440p display here and it runs off my screen

![superbigerror](https://user-images.githubusercontent.com/46382786/95541946-ad41ad00-09c2-11eb-805b-6ef80d415763.png)

**Comment by FredKruse** [comment]
The spell and grammar dialog ignores a language not supported by LT now.
@danielnaber I push also an update to the branch 5.1.2. Do you like to make a version update?

**Comment by danielnaber** [comment]
I've just released 5.1.3

**Comment by jcs090218** [comment]
Hi, I am also getting this error with the latest version, 5.3. Is `en-US` a valid language code?

**Comment by FredKruse** [comment]
@jcs090218 Did you use the LibreOffice/OpenOffice-Extension for LanguageTool or is this a bug related to Emacs?

**Comment by jcs090218** [comment]
@FredKruse This is strange since I once I have restart my computer everything seem to be working again. This occurs in windows and I don't know why. 😕 

I am not using LibreOffice and this isn't related to Emacs since I am only using the `languagetool-commandline.jar` file from command line PowerShell on Windows. Maybe this is cause by some settings from Windows? 😕 😕

**Comment by ftrxx** [comment]
Two years later I have a similar error:

java.lang.illegalArgumentException zxx is not a language code known.

In addition, LibreOffice needs additional time to open - even stalls for some time - once the LT extension activated. This is due to LT since when the extension is inactivated LO starts with no slowing down.
I have no idea how the language zxx can be eliminated.

LT does not well recognise my OS. I work with Win 11 Professional. My CPU is an Intel(R) Core(TM) i5-3230M.
LT says: 
LT office integration log from Sun Feb 04 13:15:31 CET 2024
LanguageTool 6.3 (2023-10-06 20:34:38 +0000, fb238b2)
OS: Windows 10 10.0 on amd64
LibreOffice 24.2.0.1 (The Document Foundation), en-GB
Java-Version: 1.8.0, max. Heap-Space: 512 MB, LT Heap Space Limit: 460 MB

**Comment by FredKruse** [comment]
zxx is the code for no language selected in LibreOffice.
The LT-Problem related to this will be solved in LT 6.4 see issue #9767

**Comment by FredKruse** [comment]
@ftrxx 
Did you try LT 6.3.1? Most problems are solved in this version. You get it here:  https://extensions.libreoffice.org/en/extensions/show/languagetool

**Comment by ftrxx** [comment]
I installed LT 6.3.1, thanks for the link.
Unfortunately, the same error persists .

Could this be due to the fact that LT does not well read the machine & OS information ?
LT says: OS Windows 10 10.0 on amd64
This is wrong. 
The correct information is: 
OS Windows 11 on Intel  Core i5-3230M.

Thanks in advance for your help

**Comment by dhanak** [comment]
The same issue happens on my Debian 12.4 machine, LibreOffice 7.4.7.2 40(Build:2) and LT extension v6.3.1.

Furthermore, the popup dialog, when it appears, disables all menu items in the Tools menu, including `Options...`, and they stay that way even when the dialog is closed. Apparently, the menu is stuck in an exception state.

Also note, that in `Options.../Language Settings/Writing Aids`, when I press `Edit...`, an "Edit Modules" dialog pops up, where I can allegedly control, for each language, the list of active modules. In this dialog, when I change the language to Hungarian, the `Language Tool` module doesn't even appear in the list, so one would assume that it isn't activated if the document language is Hungarian. But it doesn't have that effect.

![image](https://github.com/languagetool-org/languagetool/assets/55064/1a78d6f8-7d1a-4008-9a69-03726a95f69e)

...

Upon further inspection, I noticed the following.

1. I disabled LT altogether.
2. I opened the document. The menus stay active this time, so I can use `Tools/Language/For All Text...` to change the language of the *entire document* to Hungarian, uniformly.
3. I reenabled LT.
4. I reopened the document.

And lo and behold, no warning popup! So I'm guessing that part of the document was marked as English, or similar, which caused the LT extension's activation, which then chocked on the Hungarian parts.

**Comment by FredKruse** [comment]
@ftrxx 
> LT says: OS Windows 10 10.0 on amd64
> This is wrong.
> The correct information is:
> OS Windows 11 on Intel Core i5-3230M.
That sounds strange. Which Java version are you using? LT obtains this information from a standard Java method. If necessary, you should upgrade to a current Java version.
To narrow down the problem further: What language are you working with?

**Comment by FredKruse** [comment]
@dhanak 
I think the problem is related to using an unsupported language. I'll take a look at it.

**Comment by FredKruse** [comment]
@dhanak @ftrxx 
The issue should now be resolved in version 6.4. Please install the latest developer version **tomorrow** and test it. You can find the current developer versions here:
https://internal1.languagetool.org/snapshots/
Please provide feedback to close the issue.
