### ISSUE TITLE
[en] Testrules error snapshotLanguageTool-20201008-snapshot.zip

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3670]
With snapshot 2020-10-08 on Windows 10, `testrules `gives this message:

```
D:\LanguageTool-5.2-SNAPSHOT>testrules en
Exception in thread "main" java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.languagetool.rules.patterns.PatternRuleTest.<init>(PatternRuleTest.java:78)
        at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:677)
Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more
Running disambiguator rule tests...
Running disambiguation tests for English...
```

**Comment by danielnaber** [comment]
Should be fixed now, can you try again?

**Comment by MikeUnwalla** [comment]
Not fixed:

```
D:\LanguageTool-5.2-SNAPSHOT>testrules en
Exception in thread "main" java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.languagetool.rules.patterns.PatternRuleTest.<init>(PatternRuleTest.java:78)
        at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:677)
Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more
Running disambiguator rule tests...
Running disambiguation tests for English...
100...
200...
300...
400...
500...
600...
700...
800...
809 rules tested (8317ms)
Disambiguator tests successful.
Running XML bitext pattern tests...
Bitext pattern tests successful.
Validating false-friends.xml...
Validation successfully finished.

D:\LanguageTool-5.2-SNAPSHOT>
```

Suggestion for improvement: to make sure that the version of LT is the one that the user thinks it is, add a build date to the `testrules `message.

**Comment by danielnaber** [comment]
> Suggestion for improvement: to make sure that the version of LT is the one that the user thinks it is, add a build date to the testrules message.

I've done that now, but I'm not sure why the `ClassNotFoundException` still occurs.

**Comment by MikeUnwalla** [comment]
Works fine with LanguageTool version 5.2-SNAPSHOT (2020-10-10 18:53, c4f3386). Thanks.
