### ISSUE TITLE
[en] For category PLAIN_ENGLISH, GUI does not find an error if default=off in grammar.xml

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#421]
![lt34-snapshot-plain-english-rules](https://cloud.githubusercontent.com/assets/5816160/16159594/a0d26dd8-34bb-11e6-9dee-2e9b3b608d4c.png)

Problem occurs in LT 3.4 snapshot 2016-06-16 and earlier. I did a test in LT 3.3 and found the problem.

I tried on 2 computers.

**Comment by danielnaber** [comment]
The issue seems to be in `ConfigurationDialog` where the rule gets displayed as active even though it's off by default.

**Comment by danielnaber** [comment]
This is partially fixed now: these rules are shown as deactivated now, because that's what they are by default. However, there's another bug so that you cannot activate them yet.

**Comment by danielnaber** [comment]
This should be fixed now, can you confirm this? (i.e. the fix is in the source and will be in tonight's daily snapshot)

**Comment by MikeUnwalla** [comment]
The problem is partly corrected. If I select a rule in LanguageTool Options, LT finds the error. But, the check box in LanguageTool Options does not have a tick to show that the rule is selected.

**Comment by danielnaber** [comment]
This is what it looks here:

![rule](https://cloud.githubusercontent.com/assets/857004/17830090/c20a159a-66c1-11e6-98f7-1fed5f3feaae.png)

i.e. the rule is activated, but the containing category has no checkmark. Is it this what you mean? I'm not sure whether the containing category should be checked if only one rule is activated.

**Comment by MikeUnwalla** [comment]
My message was not clear. Sorry. The problem is that the Plain English check box does not have a tick, but all the rules are selected.

![plain-english-category-tick](https://cloud.githubusercontent.com/assets/5816160/17830345/d28dc9f8-66c0-11e6-9210-734503c1cb63.png)

**Comment by pminos** [comment]
Hi, I think that the problem is not in the GUI classes. But I need more more time to be sure.

@MikeUnwalla can you confirm that this works correct at version 3.2 but is not working correct at version 3.3?

**Comment by MikeUnwalla** [comment]
In LT 3.2 and 3.3, Plain English is selected by default. LT 3.2 gives the expected results. But LT 3.3 does not find the Plain English errors.

**Comment by pminos** [comment]
I think that this is a change of behaviour that was introduced with 8262a2828f959b2b49df437cb88e8e3786bbaf45

**Comment by pminos** [comment]
At version 3.2, a rule that belongs in a disabled category is disabled. At version 3.3 the rule is enabled. 

I think that this change of behaviour is causing this issue. So, we can revert the change at  line 635 of PatternRuleHandler.java or change the rest of the code.

**Comment by pminos** [comment]
@danielnaber I also think that we must revert 6b5f925230bdef0f94abe8ca3de7a48d37a96860 because it has no other effect except filling the config file with useless entries. A rule that is not off by default will be enabled regardless of being in the **Enabled Rules** list.

**Comment by danielnaber** [comment]
I think the issue is in: https://github.com/languagetool-org/languagetool/blob/master/languagetool-gui-commons/src/main/java/org/languagetool/gui/ConfigurationDialog.java#L103 -- categories that are off by default will never be checked, as there's `getDisabledCategoryNames()` but now `getEnabledCategoryNames()`. So we need to introduce `getEnabledCategoryNames()`, then we can revert https://github.com/languagetool-org/languagetool/commit/6b5f925230bdef0f94abe8ca3de7a48d37a96860, is that correct?

**Comment by pminos** [comment]
We can revert 6b5f925230bdef0f94abe8ca3de7a48d37a96860 regardless of this issue.

Now I am trying to understand what effect has 70792d3e8d9c6746da271286e6358f29859673e6

**Comment by pminos** [comment]
@danielnaber I think we must also revert 70792d3e8d9c6746da271286e6358f29859673e6 because a **Category** ComboBox has different logic from a **Rule** ComboBox and the commit doesn't help. 

The whole issue exists because until 3.2 a rule in disabled category was defaultOff but from 3.3 is defaultOn. So, this issue exists at version 3.3 and 3.4, we just didn't see it.

But we must also disambiguate the semantics of **enabled** value of rules that belong to disabled categories. I mean, was this change on purpose or a bug?

This is the code of 3.2, if _category.isDefaultOff()_  we call _rule.setDefaultOff()_
https://github.com/languagetool-org/languagetool/blob/v3.2/languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleHandler.java#L633

This is the code of 3.3, we use _defaultOff_ but the value is true for disabled categories
https://github.com/languagetool-org/languagetool/blob/v3.3/languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleHandler.java#L630

This is the code of the commit (8262a2828f959b2b49df437cb88e8e3786bbaf45) that introduced the issue
https://github.com/languagetool-org/languagetool/blob/8262a2828f959b2b49df437cb88e8e3786bbaf45/languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleHandler.java#L635

**Comment by danielnaber** [comment]
@pminos, is this something you could fix? I don't remember all the details of my changes, the patch isn't that small... I don't have time for this now and would put it on my TODO list.

**Comment by pminos** [comment]
@danielnaber yes, I will fix it. Just one question. If a category has **default**=**off** and a rule that belongs to that category has **no value** for **default**, then the rule should be off or on?

**Comment by danielnaber** [comment]
I think it should be off, having it on wouldn't make sense, or am I missing something?

**Comment by pminos** [comment]
@danielnaber I agree, just wanted to be sure

**Comment by MikeUnwalla** [comment]
Is the commit intended to fix the error? With LanguageTool-20160915-snapshot, problems remain.

**Comment by pminos** [comment]
@MikeUnwalla the last commit should fix the issue.

**Comment by MikeUnwalla** [comment]
@pminos, thanks, but I think that a small problem remains. The Plain English rules are OFF by default, but the box on the left contains a tick. Should the box be empty?
 
![tick-in-box-but-no-rules-selected](https://cloud.githubusercontent.com/assets/5816160/18608164/d2d5fabe-7cd9-11e6-96c5-7e8dba861666.png)

In an earlier message, @danielnaber wrote, "I'm not sure whether the containing category should be checked if only one rule is activated." Possibly, a symbol to show that only some rules are selected would be useful.
