### ISSUE TITLE
[en] Missing terms

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4354]
au pair
https://www.merriam-webster.com/dictionary/au%20pair

a priori
https://www.merriam-webster.com/dictionary/a%20priori

a posteriori
https://www.merriam-webster.com/dictionary/a%20posteriori

caveat emptor
https://www.merriam-webster.com/dictionary/caveat%20emptor

- - -

"powers that be" should be considered a term.

> The powers that **be** are going to give you a hard time.

"we" was recommended.

- - -

"if but only if" is a common logic term.

> If but only **if** their assertion were true, then we would lose.

"is" recommended.

- - -

**Typos in Terms**

Typo "ad nauseaum" -> "ad nauseam"
https://www.merriam-webster.com/dictionary/ad%20nauseam

> The topic that has been discussed and analyzed ad **nauseaum**.

LT currently recommends "nausea um".

Typo "died-in-the-wool" -> "dyed-in-the-wool"
https://dictionary.cambridge.org/us/dictionary/english/dyed-in-the-wool
https://www.merriam-webster.com/dictionary/dyed-in-the-wool

> He's a **died-in-the-wool** traditionalist where cooking is concerned - he doesn't allow any modern gadgets in the kitchen.

LT currently does not catch. (Antidote grammar checker does, which is how I caught this!)

"straw the broke the camel's back" is a common term
https://en.wikipedia.org/wiki/Straw_that_broke_the_camel%27s_back

> That was the straw that broke the **camels** back.

camels -> camel's

LT currently does not catch.

**Comment by tiff** [comment]
I fixed/implemented a few of the quick wins:
* If but only if their assertion were true, then we would lose.
* The powers that be are going to give you a hard time.
* died-in-the-wool
* That was the straw that broke the camels back.

**Comment by danielnaber** [comment]
"a priori" and "a posteriori" were already in `spelling.txt`, do we then need them in `disambiguation.xml`, too?

**Comment by Tex2002ans** [comment]
I also tested:

1. > The powers that be are going to give you a hard time.

and am still getting a "we" recommendation.

2. And while:

> ad nauseaum (typo)

doesn't recommend "nausea um" any more, it doesn't give the more helpful:

> ad nauseam

3. "If but only if" works, but now there's another hit:

> **If but** only if their assertion were true, then we would lose. their assertion were true, then we would lose.

**Grammar and Others:** Please check if you only wanted to use one conjunction here. 
"If" OR "But"

(Maybe the "If but only if" could take priority over this double conjunction rule?)

**Comment by tiff** [comment]
@danielnaber the spelling.txt doesn't work good for multiwords. Cases like "A Priori" were the first letter of every word is capitalized would still lead to a spelling error.

@Tex2002ans 
> The powers that be are going to give you a hard time.

This is definitely fixed for me. Where did you test it?

> "If but only if" works, but now there's another hit:

I fixed this. The fix will be available in the next days.

> doesn't recommend "nausea um" any more, it doesn't give the more helpful:

I created a separate issue for that:

**Comment by Tex2002ans** [comment]
> This is definitely fixed for me. 

Yes, correct. Definitely fixed now.

> Where did you test it?

I tested it on languagetool.org RIGHT before I posted, but it works fine now. Must've just needed your little magic.  :)
