### ISSUE TITLE
LibreOffice add-on doesn't detect grammar errors at top of .docx

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6200]
Hello!

I didn't report this a few days ago because of the feature freeze, as I wanted to avoid causing pressure on @FredKruse.

But here it is.

When I open this .docx in Portuguese with LibreOffice (7.3.0.1 – Windows 10), it doesn't detect the grammar errors (foreign words) in the top of the document.

All it detects is using the Java rules in English.
![pt_PT_rules_not_working_20211230](https://user-images.githubusercontent.com/5192600/147728335-823ccf12-7fe4-4a09-82d6-d3460fca8857.png)

Here is the .docx in attachment.

Thanks!
[Europass-CV-marcoagpinto_20220101_pt_blank.zip](https://github.com/languagetool-org/languagetool/files/7791778/Europass-CV-marcoagpinto_20220101_pt_blank.zip)

**Comment by FredKruse** [comment]
@marcoagpinto Just I committed a new version of the extension. I'm not really sure, if it solves the problem. The word "e-mail" is underlined but the word "Web" not. As far as I see, "Web" is not found as a match by Lt, so I don't know what I could do inside the extension. Could you please test the new version and post the results?

**Comment by marcoagpinto** [comment]
I will test with tonight's nightly.

"web" is a foreign word, so LT should suggest to place it between quotation marks or italize it.

**Comment by marcoagpinto** [comment]
@FredKruse 

It still doesn't work.

The words underlined in green close to the left icons are triggered by the general all languages Java rule, but “web” isn't triggered there as a foreign word.

See attached screenshots:
![lt_bug_foreign_1_20220107](https://user-images.githubusercontent.com/5192600/148521144-35761181-8f52-4883-9803-4b01711c848c.png)
![lt_bug_foreign_2_20220107](https://user-images.githubusercontent.com/5192600/148521167-f7345ea1-4be6-4611-837c-6060ee5e21fc.png)

**Comment by FredKruse** [comment]
@marcoagpinto @danielnaber As far as I see, the problem is related to the rules, not to the extension. When I put the String "Sítio Web: www.marcoagpinto.com (Homepage)" 
to 
languagetool.org 
or to
https://community.languagetool.org/analysis/index?lang=pt  
"Web" is also not marked as a foreign word.

**Comment by FredKruse** [comment]
@marcoagpinto: I'm not really sure: Is the problem solved? I would like to close the issue.
