### ISSUE TITLE
[pt]: "word" isn't corrected to "Word" 

### ISSUE THREAD

**Issue by MarvinErdner** [languagetool-org/languagetool#7028]
![image](https://user-images.githubusercontent.com/88431679/185555619-6bb685a5-caea-4093-bf88-2d60e0f172bd.png)

**Comment by marcoagpinto** [comment]
It has to be fixed with the spelling engine.

@jaumeortola 
?

**Comment by jaumeortola** [comment]
Fixed here for pt-BR: https://github.com/languagetool-org/languagetool/commit/d106e1e15ada51b9fafc259d5753fac4a61e91a3
For pt-PT, the suggestion was already correct. 
It is not a good solution. We still have to get rid of the Portuguese Hunspell dictionaries.

**Comment by marcoagpinto** [comment]
@jaumeortola 

How can pt-PT Hunspell dictionaries be replaced?

I still can't understand.

**Comment by jaumeortola** [comment]
> How can pt-PT Hunspell dictionaries be replaced?

We can replace the Hunspell dictionaries with Morfologik dictionaries, the file format used by most languages in LT. But the dictionaries need some cleaning. For this, we probably need many hours of work (of native speakers).
