### ISSUE TITLE
[LO add-on] Latest nightly ate 24 GB RAM - 2023-03-10

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8012]
Hello @FredKruse ,

I tried the latest nightly and my computer RAM was almost 100% used (32 GB).

When I noticed that the computer was terribly slow, I opened task manager and LibreOffice was taking 24 GB of the 32 GB of RAM.

I sent you the log file via e-mail.

Could you take a look at it?

Thanks!

**Comment by FredKruse** [comment]
This error is a mystery to me. Marco sent me a log file stating that the maximum heap space was 7262 MB. The extension limits itself and switches to a fallback mode at approx. 6500 MB, which releases all additional interfaces and deletes the cache. In principle, it is therefore impossible for the extension to allocate 24 GB of storage space. I am completely at a loss. @danielnaber do you have an idea for that?
In the log file, I noticed a problem with the internal cache allocation. I'll try to solve that. @marcoagpinto, I need your help for testing. I'll let you know when there's an update. 
However, I don't think this solves the memory problem.

**Comment by FredKruse** [comment]
By the way, I couldn't reproduce the bug.

**Comment by FredKruse** [comment]
@marcoagpinto I did a bug fix. Please test it tomorrow.

**Comment by danielnaber** [comment]
> The extension limits itself and switches to a fallback mode at approx. 6500 MB

How does it do so? Doesn't this depend on the JVM settings in LibreOffice?

**Comment by FredKruse** [comment]
The application test it: Runtime.getRuntime().maxMemory()

**Comment by danielnaber** [comment]
> The application test it: Runtime.getRuntime().maxMemory()

And how does it use that value then to limit the memory use? I don't see that in the code.

**Comment by FredKruse** [comment]
The methods MultiDocumentsHandler.isEnoughHeapSpace() and MultiDocumentsHandler.testHeapSpace() test if more the 90% of heap space is reached and do the switch to another mode.
The method OfficeTools.getCurrentHeapRatio() is used to get the information how near the extension is to the limit (the intervals of testing get shorter when the heap grows).

**Comment by danielnaber** [comment]
> The methods MultiDocumentsHandler.isEnoughHeapSpace() and MultiDocumentsHandler.testHeapSpace() test if more the 90% of heap space is reached and do the switch to another mode.

I see, but I don't know what the issue could be. Maybe it's not really the JVM that's taking the memory, but LibreOffice?

**Comment by marcoagpinto** [comment]
@FredKruse 

Maybe you are using the total RAM size instead of the heap RAM size?

**Comment by FredKruse** [comment]
The log-file @marcoagpinto sent to me shows a bug. This has to be fixed, but it will take a little time. I won't be able to look at this until the end of the week.
But I can't say, if the bugs documented in the log are related to the memory problem.

**Comment by FredKruse** [comment]
@marcoagpinto I still managed to resolve the problems in the log file. Please test it tomorrow. Please send me the log file.

**Comment by marcoagpinto** [comment]
Thanks, I will test tomorrow night.

**Comment by FredKruse** [comment]
The problems that the log file shows are solved.
@danielnaber But that still doesn't solve the memory problem. It might be related to another bug being discussed in the forum (https://forum.languagetool.org/t/lt-und-lo/8798). When highlighting a word in LO and pressing the right mouse button, LO sometimes freezes. I checked this with VisualVM. Increased CPU activity is shown (a full core or more), but the sampler is empty (I enabled it before). Normally, the thread that causes the CPU load is displayed and you can find the cause. I have no idea what else to test. Do you have any advice for me how to find the problem?

**Comment by danielnaber** [comment]
> Do you have any advice for me how to find the problem?

Once the problem occurs, you can get a stack trace using `jstack`: https://stackoverflow.com/questions/4876274/kill-3-to-get-java-thread-dump

**Comment by FredKruse** [comment]
@marcoagpinto: Did the last change solve the problem? Are there any bug reports in the log-file?
@danielnaber: The thread dump hasn't clarified the problem. After hours of tests, I'm thinking, there is a general problem in the relation between the LO-Spellchecker and the LT-extension. The extension adds the contents of the additional LT-spelling-files to LO as user dictionaries. This seems to be a problem in the mentioned cases above. I like to make a general change to the extension. The spellchecking should be done by LT too. But this will be a mayor change. It costs some time of development and some more of testing. I planned this for LT 6.2. In 6.1 we have to leave it as it is.

**Comment by marcoagpinto** [comment]
@FredKruse 

I tested it days ago, and it only consumed ~7 GB of RAM for my near 600-page thesis.

The size was increasing very slowly, but I believe it is fixed, thanks!

I haven't looked at the log file.

**Comment by marcoagpinto** [comment]
@FredKruse 

I was just checking the ~600-page thesis.

The log seems clean:
[LanguageTool_PhD_20230325.log](https://github.com/languagetool-org/languagetool/files/11070293/LanguageTool_PhD_20230325.log)

However, as I scrolled down the document, the RAM usage is increasing and when it reached 16 GB I closed LibreOffice.

![lt_RAM_20230325](https://user-images.githubusercontent.com/5192600/227743998-d3c50c8b-0284-4bdd-b38d-4de24f36f37f.png)

**Comment by marcoagpinto** [comment]
@FredKruse 

Hello!

Any news regarding this?

Have you checked if you are using the computer RAM in the code instead of the Java RAM?

**Comment by FredKruse** [comment]
I've just posted an update of the LT extension. It solves a problem with the integration of the additional LT spelling files into LO spell checker. In the past, this had triggered unexpected side effects. I'm uncertain if it solves your problem, but please test the new version and give me feedback.

**Comment by marcoagpinto** [comment]
@FredKruse 

I am very sad… 😢 😢 😢 😢 😢 😢 😢 😢 

![LT_RAM_20230404](https://user-images.githubusercontent.com/5192600/229763347-3837dbc2-4d67-442f-af9d-f2491b9608db.png)

**Comment by FredKruse** [comment]
@marcoagpinto I'm very sorry, but I have no idea. There are two strange things: 
1.) I can't reproduce the problem with my documents. 
2.) LT is written in Java. All memory, which is allocated by the software, is allocated inside the Java virtual machine - the heap space. Usually the heap space is very much smaller than 15 GB. My default documents are 300 pages, nearly 100,000 words. Usually, the heap space doesn't grow to more than 1 GB.

Did you test to load your document into LO with deactivated LT? You could open the extension manager, deactivate LT, restart LO and load your document. If the memory grows in the same way, there is a bug in LO and you have to contact the developer.

If the error only occurs when LT is installed/enabled, then we need to figure out how to find a solution.

**Comment by marcoagpinto** [comment]
@FredKruse 

![thesis_number_words_20230404](https://user-images.githubusercontent.com/5192600/229885216-466dc13c-a8a9-40d3-a69f-47e9b2ea509a.png)

Yes, a week or two ago I removed LT from the extensions and LibreOffice didn't consume much RAM.

I am not sure if this helps, but the thesis has hundreds of figures and dozens of equations and tables.

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse 

See the attached docx where I tried to kind of simulate the thesis.

The RAM usage increases until 8 GB and then slowly it starts to decrease.

Does it help?

Thanks!

[Thesis_150_figures_20230404.docx](https://github.com/languagetool-org/languagetool/files/11152307/Thesis_150_figures_20230404.docx)


![TestThesis_20230404](https://user-images.githubusercontent.com/5192600/229898197-67f4f812-e9ed-44a9-a498-6c8321e8cd95.png)

**Comment by marcoagpinto** [comment]
@FredKruse 

My wild guess is that it may be related to the IEEE bibliography.

After I added it to this DOCX, the RAM doubled or tripled.

In my thesis, I have over 400 bibliographical entries in IEEE format (dozens of pages of entries).

But it is just a wild guess.

**Comment by FredKruse** [comment]
@marcoagpinto, @danielnaber 
The good news is, I could reproduce the bug with your test file. I ran dozens of tests and found out, that the problem only appears when you load the document in DOCX format.
If you first save the file in ODT format and reload it, the problem doesn't appear. LO needs roundabout 2 GB extra memory (which is allocated as heap space) to handle a document of the given size. 
I'm totally helpless because my tests show there is no difference in what the LT extension does in both cases. LT doesn't allocate any extra memory in the DOCX case. So, the problem must exist in LO.
I have no idea for a workaround.
So, there are two possibilities (I've tested both):
1. Save the file to ODT format and do the grammar check. This works without any problem and with full function.
2. Switch (in the general tab of the LT option panel) to "paragraph check mode" - only the LO default simple grammar check is done, and no additional interfaces are used (Most of the rules will run correctly, only the paragraph overlapping rules will fail. And some additional features are missing).

I'm very sorry, that I have no better news. I hope you can live with that. I have no idea what to do next on this matter.

**Comment by marcoagpinto** [comment]
@FredKruse 

That is what I have been doing with the thesis: I change the language to PT and save as .ODT and it is a ~10 MB file.

I have a plan: when the thesis is approved by the supervisor someday, and the university accepts it, I will send it to you via e-mail.

This way you will be able to see the real issue.

😋 😋 😋 😋 😋 

Thank you for all the hard work.

**Comment by marcoagpinto** [comment]
@FredKruse 

I have e-mailed you the bibliography of my thesis in ODT format.

Just 40 pages take near 5 GB of RAM with LT.

![IEEE_with_without_LT_20230406](https://user-images.githubusercontent.com/5192600/230264170-f6588740-28d4-4ec7-9818-d4b4ad224bad.png)

Please provide some feedback after you give it a look.

Thanks!

**Comment by FredKruse** [comment]
@marcoagpinto 
I did some optimizations. 
It looks like LO allocates additional memory on LO's side and only releases it when the thread is finished. I have now taken that into account. Please test the new version and give me feedback.

**Comment by marcoagpinto** [comment]
@FredKruse 

My dear brother!

Thank you very much for trying to solve the issue.

I will test it tonight.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
@FredKruse 

Heya, Fred!

I have installed the nightly and tested it.

First I tried opening the ~600-page thesis in ODT without LanguageTool, and then with LanguageTool.

With LT, the memory kept on increasing, and I had to close LibreOffice when it reached a considerable size.

So, the bug is still there.

The good news is that I forgot to save the log file from that huge memory being taken, but then I reopened the ODT and let it ran for 2:30 minutes, and got the log from that little time.

There appears to be an issue with the log data.

Maybe by fixing the log issue it will fix the memory bug (just my 2 cents)?

Also, I kept staring at the task manager and now-and-then LibreOffice would jump from 2%-3% of CPU taken to 20%-30% (10 times more).

Thanks!

![thesis_LT_20230407](https://user-images.githubusercontent.com/5192600/230677179-a7ce6a93-3ed2-40ba-b506-2408d249527c.png)


Does the following paste of the log file help identify the issue?:
```
LT office integration log from Fri Apr 07 21:35:52 BST 2023

LanguageTool 6.2-SNAPSHOT (2023-04-07 16:44:35 +0000, 568f81e)
OS: Windows 10 10.0 on amd64
LibreOffice 7.5.2.2 (The Document Foundation), en-GB
Java-Version: 1.8.0_361, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: getCachePath: documentPath == null!
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(4): 27
CacheIO: getCachePath: documentPath == null!
MultiDocumentsHandler: getNumDoc: Document 1 created; docID = 2
Time to generate cache(4): 21
CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: getNumDoc: Document 2 created; docID = 3
MultiDocumentsHandler: runShapeCheck: start
Time to generate cache(4): 10005
```

**Comment by marcoagpinto** [comment]
Ahhhh…

And here is the log of a 10-minute run with LT set to use single-core:

```
LT office integration log from Fri Apr 07 22:05:03 BST 2023

LanguageTool 6.2-SNAPSHOT (2023-04-07 16:44:35 +0000, 568f81e)
OS: Windows 10 10.0 on amd64
LibreOffice 7.5.2.2 (The Document Foundation), en-GB
Java-Version: 1.8.0_361, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
MultiDocumentsHandler: runShapeCheck: start
Time to generate cache(4): 10967
```

**Comment by marcoagpinto** [comment]
@FredKruse 

!!!!!!!!

Hello!

It is fixed, thanks, however the internal dictionary (spelling.txt) doesn't seem to be working, all the words there appear as typos.

I installed the nightly, selected to apply the default settings in it and then selected to use more cores, then I closed LibreOffice (including the tray icon) and opened the thesis, and all words in spelling.txt appear as typos.

Now LO only uses 4,3 GB instead of 24 😄 

Thanks!

**Comment by FredKruse** [comment]
Just I have posted an update. It should solve the problem with the spelling. It works on another technical base, so please test it thoroughly.

**Comment by marcoagpinto** [comment]
I will test it tomorrow night, as I don't know if the changes will come in today's nightly.

**Comment by marcoagpinto** [comment]
@FredKruse 

Heya, Fred.

I opened the thesis and spent a bit over an hour scrolling through it.

The maximum memory it used was 5,6 GB.

The spelling.txt words no longer appear as typos.

However, I could not turn on the grammar rule that underlines unknown words:
![words_without_pos_20230414](https://user-images.githubusercontent.com/5192600/232159025-9734716a-d0b7-4a64-8154-4905bb0ed86b.png)

I tick it, and after I press “okay” it gets automatically unticked (when I reopen the settings).

Thanks!

**Comment by marcoagpinto** [comment]
Heya @FredKruse 

I activate a few more rules, and they don't work:
![rules_activated_not_working_20230415](https://user-images.githubusercontent.com/5192600/232237837-2414d23a-3307-4ecd-8680-841bd6009cb0.png)

**Comment by FredKruse** [comment]
I made numerous changes. But I'm uncertain if it solves your problem. Please test the next nightly.

**Comment by marcoagpinto** [comment]
@FredKruse 

It didn't resolve the issue. I have attached a video.

Also notice that when selecting the underline colour it should check first if the colour already exists in the recent list before adding it, or it will add over and over the same colour (see video):


https://user-images.githubusercontent.com/5192600/232978878-160608a5-ff6f-4dce-9238-b4215e23801c.mp4

**Comment by marcoagpinto** [comment]
Thanks, I will test it tonight. ❤️

**Comment by FredKruse** [comment]
@danielnaber: The application breaking problems are solved. I would like to produce a version 6.1 on the base of the actual extension code. What do you think?

**Comment by danielnaber** [comment]
>  I would like to produce a version 6.1 on the base of the actual extension code.

Feel free to create a branch for a release. Would it be based on 6.1 and only the extension code is current? That's what probably should be done if the release is called 6.1.x.

**Comment by marcoagpinto** [comment]
@FredKruse @danielnaber 

Please wait before 6.1.1, there was a regression in today's nightly.

The memory usage keeps on increasing again, and I closed LibreOffice at about 15 GB:
![languagetool_thesis_20230419](https://user-images.githubusercontent.com/5192600/233215763-917d3c7b-9ee6-47f1-bc70-0d1e1c5f2923.png)

Look at the log, there is an issue with the cache file:
```
LT office integration log from Wed Apr 19 23:24:43 BST 2023

LanguageTool 6.2-SNAPSHOT (2023-04-19 16:44:23 +0000, c2c955e)
OS: Windows 10 10.0 on amd64
LibreOffice 7.5.3.1 (The Document Foundation), en-GB
Java-Version: 1.8.0_361, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(4): 18474
Caches saved to: C:\Users\marco\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache3.lcz
Time to generate cache(6): 15127
TextLevelCheckQueue: run: Interrupt check - queue ended
Time to generate cache(6): 11144
Time to generate cache(6): 13880
```

**Comment by FredKruse** [comment]
The problem should be solved (again). Please test it as soon as possible.

**Comment by marcoagpinto** [comment]
@FredKruse 

Here it is tested "as soon as possible".

The bug is still there:
![languagetool_20230420_huge_ram_usage](https://user-images.githubusercontent.com/5192600/233463088-bc3f220f-c5d8-448d-9556-f66b59ebbbef.png)


```
LT office integration log from Thu Apr 20 19:50:54 BST 2023

LanguageTool 6.2-SNAPSHOT (2023-04-20 16:44:21 +0000, ab9bc28)
OS: Windows 10 10.0 on amd64
LibreOffice 7.5.3.1 (The Document Foundation), en-GB
Java-Version: 1.8.0_361, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(4): 15963
Caches saved to: C:\Users\marco\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache3.lcz
Caches saved to: C:\Users\marco\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache3.lcz

```

**Comment by FredKruse** [comment]
I solved some bugs and did some optimization. Please test the new version.

**Comment by marcoagpinto** [comment]
I will test it tonight. Thanks for all your efforts.

**Comment by marcoagpinto** [comment]
@FredKruse 

It is almost there.

Everything seemed to be fine as I scrolled down the document.

Then I deactivated two rules or so and every time I did that the RAM usage increased hundreds of MB, but nothing to worry about.

The real problem started when I right-clicked on one or two words that appeared as spelling mistakes, adding it/them to the standard.dictionary.

Then the RAM and CPU usage became huge, and the RAM usage kept on increasing, and I had to close LibreOffice.
![languagetool_20230422_ram_usage](https://user-images.githubusercontent.com/5192600/233799529-df4f47ed-03b0-4f93-8156-c8c2cf2fa9e9.png)

I can see that my thesis is giving too much work for me and for you… a PhD isn't easy to do, I was told… 😄 😄 😄 😄 😄 😄 
(sorry for the joke).

```
LT office integration log from Sat Apr 22 18:03:56 BST 2023

LanguageTool 6.2-SNAPSHOT (2023-04-22 16:44:24 +0000, b4aa713)
OS: Windows 10 10.0 on amd64
LibreOffice 7.5.3.1 (The Document Foundation), en-GB
Java-Version: 1.8.0_371, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: CacheCleanUp: Remove Path from CacheMap: /C:/Users/marco/Desktop/LANGUAGETOOL TESTS/PhD_thesis_marcoagpinto_IST_1Main_V0084unsent.odt
CacheIO: CacheCleanUp: Remove Path from CacheMap: /C:/Users/marco/Desktop/LANGUAGETOOL TESTS/PhD_thesis_marcoagpinto_IST_1Main_V0082unsent.odt
CacheIO: CacheCleanUp: Delete cache file: C:\Users\marco\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache2.lcz
CacheIO: CacheCleanUp: Remove Path from CacheMap: /C:/Users/marco/Desktop/LANGUAGETOOL TESTS/Thesis_150_figures_20230405.odt
CacheIO: CacheCleanUp: Delete cache file: C:\Users\marco\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache1.lcz
CacheIO: CacheCleanUp: Remove Path from CacheMap: /C:/Users/marco/Desktop/LANGUAGETOOL TESTS/PhD_thesis_marcoagpinto_IST_1Main_V0083unsent.odt
CacheIO: CacheCleanUp: Delete cache file: C:\Users\marco\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache3.lcz
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(4): 9638
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1147
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1156
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1164
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1184
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1191
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1206
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1208
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1234
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1240
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1241
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1397
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1417
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1431
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1443
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1469
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1478
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1607
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1617
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1639
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1644
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1675
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1700
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1819
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1832
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1842
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1846
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1881
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1892
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1894
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1896
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1962
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1973
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1992
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2118
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2257
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2261
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2263
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2275
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2378
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2544
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2608
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2711
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2736
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2781
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2790
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2822
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2824
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2826
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 2944
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 3273
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 3358
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 3561
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 3633
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 4546
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 4618
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 9315
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1729
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 1759
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 38
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10528
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10529
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10530
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10531
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10532
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10533
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10534
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10535
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10536
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10537
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10538
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10539
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10540
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10541
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10542
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10543
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10544
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10545
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10546
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10547
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10548
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 10549
SingleCheck: remarkChangedParagraphs: Remark: Paragraph: 38
java.lang.NullPointerException
	at org.languagetool.openoffice.FlatParagraphTools.getNumberOfAllFlatPara(FlatParagraphTools.java:518)
	at org.languagetool.openoffice.CheckRequestAnalysis.changesInNumberOfParagraph(CheckRequestAnalysis.java:733)
	at org.languagetool.openoffice.CheckRequestAnalysis.getParaFromFlatparagraph(CheckRequestAnalysis.java:426)
	at org.languagetool.openoffice.CheckRequestAnalysis.getParaPos(CheckRequestAnalysis.java:372)
	at org.languagetool.openoffice.CheckRequestAnalysis.getNumberOfParagraph(CheckRequestAnalysis.java:146)
	at org.languagetool.openoffice.SingleDocument.getCheckResults(SingleDocument.java:311)
	at org.languagetool.openoffice.SingleDocument.getCheckResults(SingleDocument.java:179)
	at org.languagetool.openoffice.MultiDocumentsHandler.getCheckResults(MultiDocumentsHandler.java:242)
	at org.languagetool.openoffice.MultiDocumentsHandler.doProofreading(MultiDocumentsHandler.java:180)
	at org.languagetool.openoffice.Main.doProofreading(Main.java:80)
```

**Comment by marcoagpinto** [comment]
Ahhhhh… the spelling mistakes, I had turned on the rule for unknown words to appear underlined in black.

So, LanguageTool had to underline all the words I added to standard.dic, I am uncertain if this information is important to you.

There were dozens, many dozens, probably of words to be underlined in black.

**Comment by FredKruse** [comment]
I had to change back to an older version because of some side effects. But I did some other optimization. Now, there is no idea left, I fear.

**Comment by marcoagpinto** [comment]
@FredKruse 

I will test it tomorrow night, since the nightly for today doesn't include the changes you have done minutes ago.

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse 

Heya, Fred,

I created a blank profile on LibreOffice for the test.

I was running my thesis for around 30–40 minutes and the RAM usage was stable at around 7 GB.

I disabled only two rules and enabled three or four.

Now and then I would scroll down.

I reached a figure and LibreOffice closed (probably a bug in LO).

I reopened the thesis and started scrolling down quickly now and then and the RAM usage started increasing until it reached 13-14 GB and I closed LO. I had it open for another around 40 minutes when this happened.

I looked at the log file and, compared to the previous one, it looks clean, except it has `Null ` in the start regarding the cache file:

```
LT office integration log from Tue Apr 25 20:42:49 BST 2023

LanguageTool 6.2-SNAPSHOT (2023-04-25 16:44:35 +0000, 4ad5344)
OS: Windows 10 10.0 on amd64
LibreOffice 7.5.3.1 (The Document Foundation), en-GB
Java-Version: 1.8.0_371, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(4): 14971
```

@FredKruse 

Could you give one last try to fix it?

Maybe fixing the `null` will solve the issue (one can hope)?

Then, we could release a 6.1.1 probably, what do you think, @danielnaber ?

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
This thesis is being very demanding, for both of us.

**Comment by marcoagpinto** [comment]
@FredKruse 

Sure, Fred.

Happy Holidays!

**Comment by FredKruse** [comment]
I made some optimizations on a deep level of a LO interface. In my test documents, the check now runs much faster and uses less memory.  Please test the new version.

**Comment by marcoagpinto** [comment]
I will test tomorrow's nightly.

Thank you for all your hard work.

**Comment by marcoagpinto** [comment]
@FredKruse 

Heya,

I created a new profile in LibreOffice to start from zero.

When I opened my .odt for the first time, I got:
![lt_20230507](https://user-images.githubusercontent.com/5192600/236698286-68c7e59f-3b7c-44fb-981a-ffbd4cf6cf53.png)

Ahhhhh… now I am going to test it.

**Comment by marcoagpinto** [comment]
@FredKruse 

This is terrible.

The memory usage seemed stable in my thesis at around 4,1 GB.

After I added one word to the standard.dic with a right-click, I have the rule that underlines unknown words in black, the memory usage doubled in just a minute or so, and I had to close LibreOffice.

Log:
```
LT office integration log from Sun May 07 20:16:29 BST 2023

LanguageTool 6.2-SNAPSHOT (2023-05-07 16:44:16 +0000, 525efe4)
OS: Windows 10 10.0 on amd64
LibreOffice 7.5.3.2 (The Document Foundation), en-GB
Java-Version: 1.8.0_371, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

java.lang.NullPointerException
	at org.languagetool.openoffice.OfficeDrawTools.isImpressDocument(OfficeDrawTools.java:147)
	at org.languagetool.openoffice.MultiDocumentsHandler.getCurrentDocument(MultiDocumentsHandler.java:275)
	at org.languagetool.openoffice.MultiDocumentsHandler$LtHelper.run(MultiDocumentsHandler.java:2054)

CacheIO: CacheCleanUp: Remove Path from CacheMap: /C:/Users/marco/Desktop/LANGUAGETOOL TESTS/PhD_thesis_marcoagpinto_IST_1Main_V0084unsent.odt
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(4): 5212
CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: removeDoc: Interrupt text level queue for document 1
MultiDocumentsHandler: removeDoc: Interrupt done
Disposed document 1 removed
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 2
Time to generate cache(4): 9226
Time to generate cache(6): 11091


```

**Comment by FredKruse** [comment]
Hi @marcoagpinto, this update solves the null pointer exception above, but not the memory problem.
I think, I could identify the problem. There is bad news: The bug is not solvable inside of LT because the problem exists on the side of LO. The interfaces between LT and LO allocate memory on both sides. LT is written in Java. The memory is limited by the heap space of the java engine. This limit is not reached. Objects that are no longer needed are freed, and the memory with them. On the side of LO, there also exists a mechanism to free no longer used memory. This seems not to work for a special interface (XFlatParagraph). This interface is definitely needed to run the text level check.
I tried to reduce the use of the interface as far as possible. It doesn't seem to be enough for your document.
But there is also good news: I did a little hack for LO 7.6, which enables LT to get some Information, which helps to reduce the use of the interfaces. Maybe this solves the problem.

**Comment by marcoagpinto** [comment]
@FredKruse 

I opened a ticket in LibreOffice's Bugzilla:
https://bugs.documentfoundation.org/show_bug.cgi?id=155232

**Comment by mikekaganski** [comment]
Hi @FredKruse,

could you please provide some kind of minimal reproducer (in Java, or in Basic, or just list a sequence of UNO calls) to get the problem in LibreOffice? I assume that some service instance is created, then destroyed on your side, but not on LibreOffice side? So possibly some kind of a simple loop of creating and destruction of the service could be such a reproducer.

Either here, or in the bug report that Marco created, would be great. Thank you!

**Comment by FredKruse** [comment]
Hi @mikekaganski, I built a dummy proofreader as LO extension. It does no real proof and no marking. It gets all XFlatParagraphs using the method "getNextPara" to get an initial paragraph and after that "getParaBefore" and "getParaAfter" from XFlatParagraphIterator and stores it in an ArrayList. The whole procedure is running in a loop. After the whole document is stored as XFlatparagraphs, the list is emptied and the XflatParagraphs are called and stored again. The loop runs 10000 times per paragraph.
You should disable or remove all grammar checkers from your LO installation and install the OXT after that. After restart of LO, load a document containing some hundred paragraphs.
In my tests the java heap space doesn't exceed 800 MB while the used memory of LO grows steady.
Here the file (the zip has to be changed to oxt):
[StarterProject.zip](https://github.com/languagetool-org/languagetool/files/11452671/StarterProject.zip)

**Comment by mikekaganski** [comment]
Thanks @FredKruse.
It seems, your extension doesn't include a source code?

**Comment by FredKruse** [comment]
Here is the source code:
[source.zip](https://github.com/languagetool-org/languagetool/files/11460784/source.zip)

**Comment by mikekaganski** [comment]
Indeed, the iterator has this curious `m_aFlatParaList` thing:

https://git.libreoffice.org/core/+/master/sw/source/core/inc/unoflatpara.hxx#127

... and each and every instance of flat para gets there, such as in getParaAfter:

https://git.libreoffice.org/core/+/master/sw/source/core/unocore/unoflatpara.cxx#536

Why do we need them...

**Comment by FredKruse** [comment]
As far as I see, there is an insertion of an XFlatParagraph at any operation into the list m_aFlatParaList. But the list will not be emptied anywhere. On the other hand, I couldn't find any reference to that list. So, it should be removed, I think.
@mikekaganski Do you work on LibreOffice and could do the fix?

**Comment by marcoagpinto** [comment]
@FredKruse @danielnaber 

@mikekaganski has committed a patch for LibreOffice 7.6 on Gerrit.

It will be available in 24/48 hours.

Fred, could you in a few days download the latest LibreOffice 7.6 nightly and check if it is fixed and if there is no need any more for a hack in LanguageTool?

Thanks!

**Comment by FredKruse** [comment]
I created a workaround on the base of the discussion above. 
@marcoagpinto Please test it.

**Comment by marcoagpinto** [comment]
@FredKruse 

Sure Fred, I will test it tonight at around 7pm or 8pm.

I will report here the results.

Notice that yesterday I tested yesterday's night, and it was consuming (and increasing) tons of RAM just by having my thesis open.

**Comment by marcoagpinto** [comment]
@FredKruse 

I believe that the memory issue is resolved.

I opened the thesis with LanguageTool settings in default (“set to default”), multiple core, activated manually some rules.

The maximum RAM it consumed from the 32 GB was 8,4 GB, but when I finished scrolling through the ~600 pages the RAM usage by LibreOffice was only 6,976.6 MB. I spent over an hour with the thesis opened.

There is still a “null” in the log:

```
LT office integration log from Sat May 13 19:03:54 BST 2023

LanguageTool 6.2-SNAPSHOT (2023-05-13 16:44:32 +0000, 6648d0c)
OS: Windows 10 10.0 on amd64
LibreOffice 7.5.3.2 (The Document Foundation), en-GB
Java-Version: 1.8.0_371, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
Time to generate cache(4): 15012
```

One thing I did notice is that adding words to the standard.dic with a right-click increased the RAM usage in 100s or even 1 GB per word (still not fixed, or it is normal?). I only added two words to standard.dic and with the unknown words rule enabled and with the colour black.

After adding the words to standard.dic the CPU load increased to the rate of 20 something percent for a long time.

But I guess it is good for the regular user if it passed my thesis test 😄 😋 … my thesis isn't an easy document.

Thank you!

**Comment by FredKruse** [comment]
I will close this issue as solved. Open a new issue with current versions if necessary.
